### PR TITLE
Generated code is not valid - value of @Generated annotation is not valid string

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
Fix for https://github.com/protostuff/protostuff/issues/84

Fixed issue with code generator, value for `@Generated` annotation must be escaped
*Also this PR fixes issue with filename prefix/suffix in PluginProtoCompiler for case when output has more than one element separated by comma.*

### CODE REVIEW

**Comment by dyu** [comment]
Looks good.
Though I'm not a fan of pulling an entire library just for string escape (and file name resolution).

**Comment by kshchepanovskyi** [comment]
I need to think about corner cases. String escape is more complex that it sound. For example, in linux:

```
konstantin@konstantin-VirtualBox:/tmp/tmp2$ touch bad\\name1.txt
konstantin@konstantin-VirtualBox:/tmp/tmp2$ touch bad\"name2.txt
konstantin@konstantin-VirtualBox:/tmp/tmp2$ ls
bad\name1.txt  bad"name2.txt
```

Also, this is not a new transitive dependency for `protostuff-core`, it is used only for maven plugin/compiler.

**Comment by kshchepanovskyi** [comment]
> Though I'm not a fan of pulling an entire library just for string escape (and file name resolution).

Upd: I reimplemented as private utility methods in `CompilerMain`, removed libraries.

**Comment by dyu** [comment]
Cool.  Thanks for re-considering it.

**Pull request merged**
