### PR TITLE
Speedup repeated/collection fields

### PR DESCRIPTION
**Pull request by dyu**
Repeated fields should have had the option to use sun.misc.unsafe from the beginning (like scalar/pojo fields had with UnsafeFieldFactory)

### CODE REVIEW

**Comment by kshchepanovskyi** [comment]
```
+270 −350
```

Looks good :)

**Comment by dyu** [comment]
Good enough for a 5.2 release?
I've been using a release script that does not need any other tools except maven and git.
```sh
#!/bin/sh

set -e

VERSION=$1
[ ! -n "$VERSION" ] && echo "Enter release version: " && read VERSION

# post-release
PR_VERSION=$2
[ ! -n "$PR_VERSION" ] && echo "Enter post-release version: " && read PR_VERSION

echo "Releasing $VERSION - are you sure? (y/n):" && read CONFIRM && [ "$CONFIRM" != "y" ] && exit 0

mvn versions:set -DnewVersion=$VERSION && \
git clean -f && git add -u && git commit -m "$VERSION" && \
mvn -Prelease deploy && mvn scm:tag && \
mvn versions:set -DnewVersion=$PR_VERSION && \
git clean -f && git add -u && git commit -m "$PR_VERSION" && \
git push origin master
```

**Comment by dyu** [comment]
err 1.5.2

**Comment by kshchepanovskyi** [comment]
That's exactly the same what maven release plugin can do with single line
command :)

13 жовт. 2016 р. 1:19 пп "David Yu" <notifications@github.com> пише:

**Comment by dyu** [comment]
It doesn't push anything until the end.  Not messing up the commits if something fails in the middle.
Now that you're not ignoring my pull request, go make a release?

**Comment by kshchepanovskyi** [comment]
Ok, I will do it.

About release plugin - it is not that bad, two things that you mentioned are not really issues (there is always a way of rolling back).

**Pull request merged**
