### PR TITLE
#154: Fix unused method arguments in XmlIOUtil

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
Fix for #154 - typical copy & paste mistake.

### CODE REVIEW

**Comment by dyu** [comment]
Yeah unfortunately, this escaped me :-/

**Comment by dyu** [comment]
And also means nobody is using xml with protostuff.
Understandable since its slow compared to the other supported formats.

**Comment by kshchepanovskyi** [comment]
Same for kvp. They are first candidates to be removed in version 2 (in
order to simplify things).


On Tue, Feb 2, 2016 at 6:42 AM, David Yu <notifications@github.com> wrote:

> And also means nobody is using xml with protostuff.
> Understandable since its slow compared to the other supported formats.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protostuff/protostuff/pull/157#issuecomment-178371062>
> .
>



-- 
Regards,

Konstantin

**Comment by dyu** [comment]
Sure.  With kvp, I think I'm the only user.  :-)
Its a specialized/unpopular usecase with nginx.

**Pull request merged**
