### PR TITLE
issue-188 fix

### PR DESCRIPTION
**Pull request by dyu**
fix for #188

### CODE REVIEW

**Comment by dyu** [comment]
@kshchepanovskyi FYI, this minimal change encodes the length differently (-(len + 1)) for boxed arrays (Integer[]) on serialization. 
The other option was to add another field (bool type) to determine whether the type is primitive or not ... as well as 7 more classes to support this custom behavior.

If this LGTY, then I'll merge it.

**Comment by tsheasha** [comment]
Hey @dyu any plans on merging this one soon?

**Comment by dyu** [comment]
Merged.

**Comment by tsheasha** [comment]
Thanks

**Comment by kshchepanovskyi** [comment]
Released version 1.5.1

**Pull request merged**
