### PR TITLE
prioritize registered classes after delegates

### LINKED ISSUE #176: Problem with serializing custom Collections
Hello,

I'm a developer of [Apache Cayenne ORM framework](https://github.com/apache/cayenne). We are going to use Protostuff runtime object graph serialization for our ROP functionality instead of Hessian. So, I'm working on [cayenne-protostuff module](https://github.com/thinline72/cayenne/tree/cayenne-protostuff/cayenne-protostuff).

Unfortunately, I faced the problem with serializing custom collections. I use `protostuff.runtime.collection_schema_on_repeated_fields=true` and `protostuff.runtime.morph_collection_interfaces=true`. Even if I provide custom schema or preregister runtime generated schema, Protostuff treats my custom collection as Collection during serialization process and doesn't serialize any additional fields. Below are example of usage and some details about what happens on Protostuff side.

There is a custom List implementation [PersistentObjectList](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/util/PersistentObjectList.java) in Cayenne, which is extended from [RelationshipFault](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/util/RelationshipFault.java). RelationshipFault has two important fields "relationshipOwner" and "relationshipName".

So if I serialize PersistentObjectList directly (as parent), it works fine:
```java
@Test
public void testPersistentObjectListAsParent() {
    Schema<PersistentObjectList> schema = RuntimeSchema.getSchema(PersistentObjectList.class);
    PersistentObjectList list = new PersistentObjectList(new MtTable1(), "test");

    byte[] bytes = GraphIOUtil.toByteArray(list, schema, LinkedBuffer.allocate());
    PersistentObjectList list0 = schema.newMessage();
    GraphIOUtil.mergeFrom(bytes, list0, schema);

    assertNotNull(list0.getRelationshipOwner()); // true, {<no id>; transient; []}
    assertNotNull(list0.getRelationshipName()); // true, test
}
```

But usually PersistentObjectList is a nested object. For simplicity, I just wrap it by simple Wrapper.
```java
public class Wrapper implements Serializable {
    public Object data;
    
    public Wrapper(Object data) {
        this.data = data;
    }
}

@Test
public void testPersistentObjectListWithWrapper() {
    Schema<Wrapper> schema = RuntimeSchema.getSchema(Wrapper.class);
    PersistentObjectList list = new PersistentObjectList(new MtTable1(), "test");

    byte[] bytes = GraphIOUtil.toByteArray(new Wrapper(list), schema, LinkedBuffer.allocate());
    Wrapper result = schema.newMessage();
    GraphIOUtil.mergeFrom(bytes, result, schema);
    PersistentObjectList list0 = (PersistentObjectList) result.data;

    assertNotNull(list0.getRelationshipOwner()); // false, null
    assertNotNull(list0.getRelationshipName()); // false, null
}
```

So, what happens on Protostuff side. Here is some kind of stack-trace:
[GraphIOUtil.java:261](https://github.com/protostuff/protostuff/blob/master/protostuff-core/src/main/java/io/protostuff/GraphIOUtil.java#L261)
[RuntimeSchema.java:457](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeSchema.java#L457) // Here Protostuff gets a field with PersistentObjectList
[RuntimeUnsafeFieldFactory.java:1231](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeUnsafeFieldFactory.java#L1231) // Here it starts to writeObject with PersistentObjectList
[GraphProtostuffOutput.java:64](https://github.com/protostuff/protostuff/blob/master/protostuff-core/src/main/java/io/protostuff/GraphProtostuffOutput.java#L64)
[ObjectSchema.java:356](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L356)
[ObjectSchema.java:945](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L945) // Here it treats PersistentObjectList as Collection
[IdStrategy.java:554](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/IdStrategy.java#L554) // And here it applies Protostuff's COLLECTION_SCHEMA and DYNAMIC_VALUE_SCHEMA, which doesn't serialize any additional fields

Am I doing something wrong? Is it another way how to deal with custom collections?
I think the main issue is that Protostuff doesn't check for any registered schemas here [ObjectSchema.java:716](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L716) before checking for Collection (or whatever else). So, how about to check for existing schemas, as it's already done for [delegates](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L718)?

Thanks!

### PR DESCRIPTION
**Pull request by dyu**
Fixes #176

Without this change, #176 could still be resolved by registering a delegate.

### CODE REVIEW

**Comment by kshchepanovskyi** [comment]
@dyu Looks good. Merge and make a release?

**Comment by dyu** [comment]
Ok.

**Comment by thinline72** [comment]
Hi @dyu,
Thanks for your help!

Unfortunately, it doesn't resolve the problem.
[It checks](https://github.com/dyu/protostuff/blob/8b09091191bf5b997a22d01309e293c51a76e784/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeFieldFactory.java#L227) class of field type. I mean with wrapper it will be Object class, not concrete class.

Here is a test and my ugly solution: https://github.com/thinline72/protostuff/commit/838a59d989d0a45562542c868588662a86ad502d

**Comment by dyu** [comment]
You need to register a custom schema for ```PersistentObjectList``` to make it work.
This will not work because the latter call will already initialize the schema before it can be registered:
```java
RuntimeSchema.register(PersistentObjectList.class, RuntimeSchema.getSchema(PersistentObjectList.class));
```

Do this instead:
```java
// I guess this needs to be documented
// This is effectively registering the schema which will now take precedence based on the last PR
RuntimeSchema.map(PersistentObjectList.class, PersistentObjectList.class)
```

**Comment by dyu** [comment]
Disregard the RuntimeSchema.map suggestion above.
I think we'll probably need to add an overload method ```register``` without the schema arg and lazy-initialize it differently to make it work.

**Comment by thinline72** [comment]
I'm a little bit confused. Could you explain me which steps should I do based on my small example [CustomCollectionTest.java](https://github.com/thinline72/protostuff/blob/838a59d989d0a45562542c868588662a86ad502d/protostuff-runtime/src/test/java/io/protostuff/runtime/CustomCollectionTest.java)?

Also, solution that I suggested works fine with this test (with Wrapper(Object object)), but fails with deeper graph of objects. [PolymorphicCollectionSchema](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/PolymorphicCollectionSchema.java#L543) is used for writing. It happens when custom collection (PersistentObjectList) is declared as List field (not object). For example Wrapper(List list) in my test.

**Comment by dyu** [comment]
@thinline72 To make your code work now, use a delegate.
I realize that adding support for this PR will require a lot of changes (and a little bit of runtime overhead)

Here's how to do it:
```java
    @SuppressWarnings("serial")
    static final class PersistentObjectList<T> extends ArrayList<T>
    {
        public final int id;
        
        public PersistentObjectList()
        {
            id = 0;
        }
        
        public PersistentObjectList(int id)
        {
            this.id = id;
        }
    }
    
    static final class TestWrapper
    {
        Object obj;
    }
    
    @SuppressWarnings("rawtypes")
    static final class PersistentObjectListDelegate implements Delegate<PersistentObjectList>
    {
        
        final RuntimeSchema<PersistentObjectList> schema;
        
        public PersistentObjectListDelegate(IdStrategy strategy)
        {
            schema = RuntimeSchema.createFrom(PersistentObjectList.class, strategy);
        }

        @Override
        public FieldType getFieldType()
        {
            return FieldType.MESSAGE;
        }

        @Override
        public PersistentObjectList readFrom(Input input) throws IOException
        {
            return input.mergeObject(null, schema);
        }

        @Override
        public void writeTo(Output output, int number, PersistentObjectList value, boolean repeated)
                throws IOException
        {
            output.writeObject(number, value, schema, repeated);
        }

        @Override
        public void transfer(Pipe pipe, Input input, Output output, int number, boolean repeated)
                throws IOException
        {
            output.writeObject(number, pipe, schema.getPipeSchema(), repeated);
        }

        @Override
        public Class<?> typeClass()
        {
            return PersistentObjectList.class;
        }
    };
    
    public void testOverrideArrayList() throws IOException
    {
        DefaultIdStrategy strategy = (DefaultIdStrategy)RuntimeEnv.ID_STRATEGY;
        strategy.registerDelegate(new PersistentObjectListDelegate(strategy));
        
        TestWrapper wrapper = new TestWrapper();
        wrapper.obj = new PersistentObjectList<Object>(15);
        
        Schema<TestWrapper> schema = RuntimeSchema.getSchema(TestWrapper.class);
        
        byte[] data = toByteArray(wrapper, schema);
        
        TestWrapper parsed = schema.newMessage();
        mergeFrom(data, 0, data.length, parsed, schema);
        
        assertNotNull(parsed.obj);
        assertTrue(parsed.obj instanceof PersistentObjectList);
        
        @SuppressWarnings("unchecked")
        PersistentObjectList<Object> list = (PersistentObjectList<Object>)parsed.obj;
        assertEquals(15, list.id);
    }
```

**Comment by dyu** [comment]
To make it re-usable:
```java
    static final class EagerDelegate<T> implements Delegate<T>
    {
        final Class<T> typeClass;
        final IdStrategy strategy;
        final RuntimeSchema<T> schema;
        
        public EagerDelegate(final Class<T> typeClass, IdStrategy strategy)
        {
            this.typeClass = typeClass;
            this.strategy = strategy;
            schema = RuntimeSchema.createFrom(typeClass, strategy);
        }
        
        @Override
        public FieldType getFieldType()
        {
            return FieldType.MESSAGE;
        }

        @Override
        public T readFrom(Input input) throws IOException
        {
            return input.mergeObject(null, schema);
        }

        @Override
        public void writeTo(Output output, int number, T value, boolean repeated)
                throws IOException
        {
            output.writeObject(number, value, schema, repeated);
        }

        @Override
        public void transfer(Pipe pipe, Input input, Output output, int number, boolean repeated)
                throws IOException
        {
            output.writeObject(number, pipe, schema.getPipeSchema(), repeated);
        }

        @Override
        public Class<?> typeClass()
        {
            return typeClass;
        }
    };
    
    /**
     * For objects that have circular dependencies.
     */
    static final class LazyDelegate<T> implements Delegate<T>
    {
        final Class<T> typeClass;
        final IdStrategy strategy;
        private volatile RuntimeSchema<T> schema;
        
        public LazyDelegate(final Class<T> typeClass, IdStrategy strategy)
        {
            this.typeClass = typeClass;
            this.strategy = strategy;
        }
        
        private RuntimeSchema<T> getSchema()
        {
            RuntimeSchema<T> schema = this.schema;
            if (schema == null)
            {
                synchronized (this)
                {
                    if ((schema = this.schema) == null)
                        this.schema = schema = RuntimeSchema.createFrom(typeClass, strategy);
                }
            }
            
            return schema;
        }

        @Override
        public FieldType getFieldType()
        {
            return FieldType.MESSAGE;
        }

        @Override
        public T readFrom(Input input) throws IOException
        {
            return input.mergeObject(null, getSchema());
        }

        @Override
        public void writeTo(Output output, int number, T value, boolean repeated)
                throws IOException
        {
            output.writeObject(number, value, getSchema(), repeated);
        }

        @Override
        public void transfer(Pipe pipe, Input input, Output output, int number, boolean repeated)
                throws IOException
        {
            output.writeObject(number, pipe, getSchema().getPipeSchema(), repeated);
        }

        @Override
        public Class<?> typeClass()
        {
            return typeClass;
        }
    };
```

**Comment by dyu** [comment]
```
 It happens when custom collection (PersistentObjectList) is declared as List field (not Object)
```
I somehow missed this yesterday.  I was able to reproduce what you got (the delegates didn't help).
protostuff-collectionschema treats maps/collections as containers and simply serialize their elements using a derived schema.  So on deser, Collection.add and Map.put are used to restore state.
The way to solve this is to force List/Map fields to be serialized using ObjectSchema (either based on field annotation or system property).

**Comment by thinline72** [comment]
Hi @dyu,
Many thanks to you for your help! I'm currently trying to apply your suggestions. 

> The way to solve this is to force List/Map fields to be serialized using ObjectSchema (either based on field annotation or system property).

I'm wondering which annotation or system property should I use?

**Comment by thinline72** [comment]
After trying your suggestions, I have the following results:
For
```java
static final class Wrapper {
    Object obj;
}
```
If I use ProtostuffIOUtil, it works fine. If I use GraphIOUtil, I have Wrapper in Wrapper in Wrapper ... (recursion). 

For
```
static final class Wrapper {
    List obj;
}
```
Both ProtostuffIOUtil and GraphIOUtil don't serialize extra fields.

**Comment by dyu** [comment]
https://github.com/protostuff/protostuff/pull/180 should be able to do it.
Set any of the following system props depending on your needs.
```
    -Dprotostuff.runtime.pojo_schema_on_collection_fields=true
    -Dprotostuff.runtime.pojo_schema_on_map_fields=true
```
And then:
```java
// newly added (the other method expects a custom schema ... e.g. hand-written)
RuntimeSchema.register(MyCustomerCollection.class);
```

**Comment by thinline72** [comment]
Hi @dyu,
Thank you very much! 
It looks really well and should help. I'll try it tomorrow.

**Comment by thinline72** [comment]
Hi @dyu,
Thanks a lot, looks like it works well. 
But after your changes I faced another problem, which hasn't happened before. Now I cannot serialize class without fields. For example simple [BootstrapMessage](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/remote/BootstrapMessage.java):
```java
public class BootstrapMessage implements ClientMessage {
    @Override
    public String toString() {
        return "Bootstrap";
    }
}
```

I have the following RuntimeException:
```
java.lang.RuntimeException: All fields were excluded for org.apache.cayenne.remote.BootstrapMessage on group 0

	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:167)
	at io.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:115)
	at io.protostuff.runtime.DefaultIdStrategy$Lazy.getSchema(DefaultIdStrategy.java:709)
	at io.protostuff.runtime.ObjectSchema.writeObjectTo(ObjectSchema.java:1008)
	at io.protostuff.runtime.ObjectSchema.writeTo(ObjectSchema.java:356)
	at io.protostuff.GraphProtostuffOutput.writeObject(GraphProtostuffOutput.java:64)
	at io.protostuff.runtime.RuntimeUnsafeFieldFactory$15$1.writeTo(RuntimeUnsafeFieldFactory.java:1232)
	at io.protostuff.runtime.RuntimeSchema.writeTo(RuntimeSchema.java:472)
	at io.protostuff.GraphIOUtil.toByteArray(GraphIOUtil.java:261)
```

Looks like [this one](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/IdStrategy.java#L125) should return the schema if `primaryGroup` is null, as it was before (in 1.4.2).

**Comment by dyu** [comment]
```
Now I cannot serialize class without fields
```
Yes.  That is expected.  The workaround for that is to register a hand-written schema for that class.
Usually, for that class, you could have written it as an enum that implements ClientMessage.

**Comment by kshchepanovskyi** [comment]
> Yes. That is expected.

@dyu why is it expected? Why there is this limit?

**Comment by dyu** [comment]
It corrects a user when he misplaces a Tag/Exclude annotation.
Or you register LinkedList.class and then getting zero data on deser because all its fields are transient.

We could accept empty objects with no fields through a flag if that is desirable.

**Comment by kshchepanovskyi** [comment]
> It corrects a user when he misplaces a Tag/Exclude annotation.

This is not that sort of problems that library should detect.
It can be totally valid case when users remove (not exclude) last field from a message as a part of a deprecation process, but keeping message empty.

There is no need to have a flag for this, it should be just fixed.

**Comment by dyu** [comment]
Obviously we differ in opinions.  The default behavior has been to throw an exception.
Like heck, it has been there since the start because the initial use-case was to output what the generated-pojos generate.

If you look at all the flags/options carefully, there are many defaults in there that doesn't fit a certain use-case.
If you want to change the default behavior, set a flag.

**Comment by dyu** [comment]
Remember that the compiler did not allow messages with no fields.  You'd get an error there as well.

**Comment by kshchepanovskyi** [comment]
> Remember that the compiler did not allow messages with no fields. You'd get an error there as well.

This was fixed long time ago.

**Comment by dyu** [comment]
```
This was fixed long time ago.
```
Yea I know.  I did say 'did' (but wrong grammar on the second sentence).  I was making a point about consistency.

**Comment by kshchepanovskyi** [comment]
Ok ) 
In any case, my point still is same: there are valid cases for empty classes (w/o fields), and we should not throw an exception for such classes. Decision is up to you (I do not use `protostuff-runtime` in my projects anymore, we completely migrated to generated code as it is more predictable).

**Comment by dyu** [comment]
@kshchepanovskyi Hmm.  I just found out that this has been removed from RuntimeSchema.
```
        if(fields.isEmpty())
        {
            throw new RuntimeException("Not able to map any fields from " + 
                    typeClass + ".  All fields are either transient/static.");
        }
```
So it looks like the default behavior had already been changed in versions 1.3.x and above?
I assumed that this code was in place as I remember it.
Upon taking another look at the stacktrace posted by @thinline72, it looks like a bug from my last PR.

**Comment by dyu** [comment]
@thinline72 https://github.com/protostuff/protostuff/pull/184 should do it.
I failed to take a closer look at your stacktrace, my bad.

**Comment by dyu** [comment]
https://github.com/protostuff/protostuff/pull/185 makes it consistent to always allow empty messages (and reverts to the old IdStrategy.newSchema behavior)

**Comment by thinline72** [comment]
Thanks a lot!

**Comment by thinline72** [comment]
Hello,

I would like to know could I use a custom Delegate for custom collection now?

For example I have [this collection](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/ObjectContextChangeLog.java#L158). As you could see, it's immutable and has writeReplace() method for serialization purposes. As protostuff doesn't support neither writeReplace() nor readResolve(), I wrote custom Delegate like this one (not final version) and registered it.
```java
public class ObjectContextChangeLogSubListDelegate implements Delegate<ObjectContextChangeLog.SubList> {

    final RuntimeSchema<ArrayList> schema;

    public ObjectContextChangeLogSubListDelegate(IdStrategy strategy) {
        this.schema = RuntimeSchema.createFrom(ArrayList.class, strategy);
    }

    @Override
    public WireFormat.FieldType getFieldType() {
        return WireFormat.FieldType.MESSAGE;
    }

    @Override
    public ObjectContextChangeLog.SubList readFrom(Input input) throws IOException {
        ArrayList list = input.mergeObject(null, schema);

        return new ObjectContextChangeLog.SubList(list, 0, list.size());
    }

    @Override
    public void writeTo(Output output, int number, ObjectContextChangeLog.SubList value, boolean repeated) throws IOException {
        ObjectContextChangeLog.SubList list = (ObjectContextChangeLog.SubList) value;
        ArrayList subList = (ArrayList) list.writeReplace();

        output.writeObject(number, subList, schema, repeated);
    }

    @Override
    public void transfer(Pipe pipe, Input input, Output output, int number, boolean repeated) throws IOException {
        throw new UnsupportedOperationException(
                "Method transfer isn't supported for ObjectContextChangeLogSubListDelegate");
    }

    @Override
    public Class<?> typeClass() {
        return ObjectContextChangeLog.SubList.class;
    }
}
```

But Protostuff doesn't honored my delegate and use PolymorphicPojoCollectionSchema. So, Protostuff writes and reads it as ObjectContextChangeLog.SubList and throws
`
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at io.protostuff.runtime.IdStrategy$8.mergeFrom(IdStrategy.java:503)
`
while trying to deserialize.

BTW, Why doesn't Protostuff support writeReplace() and readResolve()?

**Comment by thinline72** [comment]
Anyway, looks like my problem could be solved by registering custom CollectionSchema.MessageFactory.

**Comment by kshchepanovskyi** [comment]
> BTW, Why doesn't Protostuff support writeReplace() and readResolve()?

These methods might return _anything_ - it might lead to problems when class is used with both protostuff & java serialization. If there is a need to have something similar, we should use different methods.

**Pull request merged**
