### PR TITLE
Added support for private constructors in DefaultIdStrategy

### PR DESCRIPTION
**Pull request by danwue**

### CODE REVIEW

**Comment by dyu** [comment]
The formatting is messed up.

**Comment by kshchepanovskyi** [comment]
Ups, did not notice. This is the only java project I work on that has curly braces starting on new lines.

**Comment by kshchepanovskyi** [comment]
@dyu it should be possible to add maven checkstyle plugin, and forget about formatting issues once and forever.

**Comment by dyu** [comment]
@kshchepanovskyi I haven't used that but sure, if it fixes the formatting issues.
The style is rarely used in java projects.
The notable ones I know of, are jetty and cassandra.
I inherited the style from the former when I got involved and preferred that style from then on.

**Pull request merged**
