### PR TITLE
add protostuff-msgpack module

### PR DESCRIPTION
**Pull request by alexshvid**

### CODE REVIEW

**Comment by dyu** [comment]
Great job.
Can you make the code style consistent?  Other than that, it looks good.

**Comment by alexshvid** [comment]
There are two options to serialize data in msgpack:
1) Streaming (that is implemented). Each object is the sequence of [tagNum][Value][tagNum][Value][0] that ends by 0 (tagNum). So, embedded objects very easy to recognize, and no need internal memory for Output stream to handle this logic. That is implemented. Arrays are implemented by repeating tagNum, so it is not efficient by the space, but better in performance.
2) Collect all data for the object, serialize it as a Map<Integer, Value>. Serialize collections as msgpack arrays. Basically it will require to hold all data in ouput, because msgpack needs headers with mapSize and arrayLength. Practically, we will have objects that are Maps with Arrays, so it is much better for cross platform serialization. Also we can use fieldName instead of tagNum in the key, so will give Json like implementation. The only challenge is that msgpack needs size before each complex collection (Map or Array). Therefore I would need to use memory in Output stream to handle this.
Not sure what direction is better. 1) - 100% implemented, 2)- idea

**Comment by alexshvid** [comment]
Implemented 2 option. All objects now are compatible with 
http://kawanet.github.io/msgpack-lite/

**Comment by dyu** [comment]
I've added you to the org so you can freely improve the impl.
One area to improve in is efficiency.
Currently, your impl allocates 2 Immutable*ValueImpl for every single field during serialization.
That's a lot of overhead that would definitely slow down serialization.

**Comment by alexshvid** [comment]
I totally agree about performance, and my performance tests show a big area of improvement msgpack itself. So, I am thinking about MsgpackXOutput based on LinkedBuffer and WriteSession.

**Comment by dyu** [comment]
Cool.  Thanks for the impl. :+1:

**Pull request merged**
