### PR TITLE
RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT is invalid for IdStrategy#ARRAY_STRING_SCHEMA

### PR DESCRIPTION
**Pull request by fengjiachun**
https://github.com/protostuff/protostuff/issues/251

### CODE REVIEW

**Comment by fengjiachun** [comment]
I only did one thing, moving the construction of XX_SCHEMA into the constructor of IdStrategy.

Let me add some test-cases

**Comment by dyu** [comment]
@fengjiachun thanks!  I ran your new tests without your patch to IdStrategy applied, and all the tests pass.
```
mvn test -Dtest=*NullArrayElementTest -Dprotostuff.runtime.allow_null_array_element=true
```

I was expecting it to fail (which requires your patch to make it pass)

**Comment by dyu** [comment]
mvn test -Dtest=*NullArrayElementTest -Dprotostuff.runtime.allow_null_array_element=true
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building protostuff :: runtime 1.6.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ protostuff-runtime ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ protostuff-runtime ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/dyu/dev/gh-protostuff/protostuff/protostuff-runtime/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ protostuff-runtime ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ protostuff-runtime ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/dyu/dev/gh-protostuff/protostuff/protostuff-runtime/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ protostuff-runtime ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ protostuff-runtime ---
[INFO] Surefire report directory: /data/dyu/dev/gh-protostuff/protostuff/protostuff-runtime/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.protostuff.runtime.ProtobufNullArrayElementTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec - in io.protostuff.runtime.ProtobufNullArrayElementTest
Running io.protostuff.runtime.ProtostuffNullArrayElementTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec - in io.protostuff.runtime.ProtostuffNullArrayElementTest

Results :

Tests run: 20, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.272 s
[INFO] Finished at: 2018-09-19T20:50:41+08:00
[INFO] Final Memory: 14M/212M
[INFO] ------------------------------------------------------------------------
```

**Comment by fengjiachun** [comment]
I'm on macos10.13.6, the fields are initialized before the constructor(before IdStrategy.flags )

**Comment by fengjiachun** [comment]
Do you mind run the test again? use -Dtest=*NullArrayElementInObjectArrayTest
I guess you may have run the wrong test case

**Comment by dyu** [comment]
Nice catch.  I did run the wrong tests.
Now with the right tests, I now get failures.
Thanks @fengjiachun

**Comment by fengjiachun** [comment]
:)

**Pull request merged**
