### PR TITLE
Improve @Tag processing

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
* throw `IllegalArgumentException` if `@Tag`'s value is out of range
* use map instead of array (reduces amout of memory needed for schema), prevents from getting `OutOfMemoryError`
* small refactoring, deleted all unused constructors from `MappedSchema`
* add unit tests for `@Tag`'s value

Fix for https://github.com/protostuff/protostuff/issues/81

### CODE REVIEW

**Comment by dyu** [comment]
Not a fan of adding a full library for a single IntMap.  
Also, please don't totally replace the old behavior.
It works well (perfect) for classes not owned by you ... which was the goal of protostuff-runtime (along with being as efficient a possible)

Instead, you can subclass MappedSchema that wraps an IntMap.   Then you can choose this impl when the fields are sparse.
RuntimeSchema will need to be refactor to wrap a MappedSchema instead of extending it.
The wrapped impl will depend on the sparseness.

**Comment by kshchepanovskyi** [comment]
Agree, we must preserve existing behavior for classes not-owned by user - from performance perspective it is optimal.

About library for single data structure - need to think. 
[Size of jar is 2.5mb](http://mvnrepository.com/artifact/net.sf.trove4j/trove4j/3.0.3), not too big but not small too. In general, I do not like to "reinvent the wheel".

**Comment by kshchepanovskyi** [comment]
> RuntimeSchema will need to be refactored to wrap a MappedSchema instead of extending it.

This refactoring is complex and affects many other classes, because MappedSchema-s fields are usually accessed directly.

**Comment by kshchepanovskyi** [comment]
Let's run some benchmarks before doing refactoring.

**Comment by dyu** [comment]
You can use ```HashMap<Integer, Object>```.
If someone really wants performance, then they'd avoid making a sparse tag definition.

If you want a primitive map impl, you can source-import only the IntMap impl from FastUtil/HPPC/colt/etc (as long as the license is compatible)
Here's a benchmark I found:
https://github.com/chrisvest/primitive-collections-benchmark

**Pull request closed without merging**
